share:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: QA05235.west-europe.azure
      user: BI
      password: SnowPFBI11833?
      role: TRANSFORMER
      database: SHARE_DWH_MART_DEV
      warehouse: TRANFORMING
      schema: DEV
      threads: 5
      client_session_keep_alive: False
      #query_tag: "NA"
    prod:
      type: snowflake
      account: QA05235.west-europe.azure
      user: BI
      password: SnowPFBI11833?
      role: TRANSFORMER
      database: SHARE_DWH_MART_PROD
      warehouse: TRANFORMING
      schema: PROD
      threads: 5
      client_session_keep_alive: False
      #query_tag: "NA"